import Navbar from "@/components/Navbar";
import "./globals.css";
import { Sora } from "next/font/google";
import StateProvider from "@/components/State";
import { NextAuthProvider } from "@/components/Provider";

const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <StateProvider>
            <Navbar />
            {children}
          </StateProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
